server:
  port: 8001

spring:
  datasource:
    url: jdbc:h2:mem:credit-application-system
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
