server:
  port: 8001

spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
