server:
  port: 8001

spring:
  datasource:
    url: jdbc:h2:mem:credit-application-system
    username: sa
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
